<!DOCTYPE html>
<html lang="en"><head>
<script src="lecture_files/libs/clipboard/clipboard.min.js"></script>
<script src="lecture_files/libs/quarto-html/tabby.min.js"></script>
<script src="lecture_files/libs/quarto-html/popper.min.js"></script>
<script src="lecture_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="lecture_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lecture_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="lecture_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="WANG Chao, NEPOTE Luca, FRANZESE Giulio, MICHIARDI Pietro — EURECOM">
  <meta name="dcterms.date" content="2026-04-13">
  <title>Relative Entropy Estimation in Function Space</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="lecture_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="lecture_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="lecture_files/libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link href="lecture_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="lecture_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="lecture_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="lecture_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Relative Entropy Estimation in Function Space</h1>
  <p class="subtitle">Theory and Applications to Trajectory Inference</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
WANG Chao, NEPOTE Luca, FRANZESE Giulio, MICHIARDI Pietro — EURECOM 
</div>
</div>
</div>

  <p class="date">2026-04-13</p>
</section>
<section>
<section id="introduction" class="title-slide slide level1 center">
<h1>Introduction</h1>

</section>
<section id="trajectory-inference-in-single-cell-genomics" class="slide level2">
<h2>Trajectory Inference in Single-Cell Genomics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Goal:</strong> Reconstruct dynamical processes of cellular development.</li>
<li><strong>Observations:</strong> Snapshots — independent samples from time-indexed marginals <span class="math inline">\(\mu_{t_1}, \mu_{t_2}, \dots\)</span></li>
<li><strong>Destructive measurements:</strong> Individual cells cannot be tracked longitudinally.</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/eb_snapshots.png" style="width:100.0%"></p>
<figcaption>Embryoid Body snapshots</figcaption>
</figure>
</div>
</div></div>
<blockquote>
<p><strong>The fundamental challenge:</strong> We observe <em>where</em> cells are at each time point, but never <em>how</em> individual cells move between them.</p>
</blockquote>
</section>
<section id="mathematical-formulation" class="slide level2">
<h2>Mathematical Formulation</h2>
<ul>
<li>Let <span class="math inline">\((\mu_{t_i})_{i=1}^T\)</span> be observed marginals at discrete times <span class="math inline">\(t_1 &lt; \cdots &lt; t_T\)</span></li>
<li>A <strong>trajectory inference method</strong> outputs a path measure <span class="math inline">\(\nu\)</span> on <span class="math inline">\(\mathcal{H}\)</span> whose time-<span class="math inline">\(t_i\)</span> marginals match the observations</li>
<li>ODE-based methods (TIGON, AM): deterministic flows</li>
<li>SDE-based methods (SBIRR, vSB, MSBM): stochastic Schrödinger Bridge-type flows</li>
<li>Drift-Diffusion methods (MFL): path-space optimization, min-entropy w.r.t. Wiener measure</li>
</ul>
<blockquote>
<p><strong>Non-identifiability:</strong> Infinitely many path measures <span class="math inline">\(\nu\)</span> are consistent with any finite set of marginals <span class="math inline">\(\mu_{t_1}, \ldots, \mu_{t_T}\)</span>.</p>
</blockquote>
</section>
<section id="the-evaluation-problem" class="slide level2 scrollable">
<h2>The Evaluation Problem</h2>
<p><strong>Standard practice:</strong> evaluate TI methods by marginal reconstruction on held-out snapshots</p>
<p>Common metrics: EMD (<span class="math inline">\(W_1\)</span>), <span class="math inline">\(W_2\)</span>, SWD, MWD, MMD</p>
<p><strong>Why this is fundamentally limited:</strong></p>
<ol type="1">
<li>Marginals do not constrain how states at different times are <em>coupled</em></li>
<li>Distinct trajectory models can match marginals while inducing very different path distributions</li>
<li>The true object of interest — the path measure <span class="math inline">\(\nu\)</span> — is invisible to marginal-only criteria</li>
</ol>
<p><span class="math inline">\(\Rightarrow\)</span> Need a metric that acts <strong>directly on distributions over trajectories</strong></p>
</section>
<section id="finite-dimensional-vs-function-spaces" class="slide level2">
<h2>Finite-Dimensional vs Function Spaces</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/conceptual_figure_snapshots_icml.png" style="width:100.0%"></p>
<figcaption>Finite-Dimensional Space (Snapshot Distributions)</figcaption>
</figure>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/conceptual_figure_trajectories_icml.png" style="width:100.0%"></p>
<figcaption>Function Space (Distribution over Trajectories)</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="why-marginal-metrics-fail" class="slide level2">
<h2>Why Marginal Metrics Fail</h2>
<p>Empirical failure modes:</p>
<ul>
<li><strong>Temporal instability:</strong> the same method can rank best at some snapshots and worst at others</li>
<li><strong>Metric disagreement:</strong> at a fixed timepoint, EMD, <span class="math inline">\(W_2\)</span>, MMD can produce conflicting rankings</li>
<li><strong>Kernel saturation:</strong> MMD with fixed bandwidth becomes insensitive to large discrepancies</li>
<li><strong>Training marginals bias:</strong> methods matching training marginals may deteriorate at intermediate times</li>
</ul>
<blockquote>
<p><strong>Metrics inconsistency:</strong> Marginals are insufficient statistics for path measures. Different metrics lead to different rankings across (or for the same) snapshots.</p>
</blockquote>

<img data-src="figures/tab_petal_marginals.png" style="width:85.0%" class="r-stretch quarto-figure-center"><p class="caption">Petal trajectories: marginal metrics at each validation time <span class="math inline">\(\tau\)</span></p></section>
<section id="motivating-example-same-marginals-different-dynamics" class="slide level2">
<h2>Motivating Example: Same Marginals, Different Dynamics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Petal dataset, <span class="math inline">\(\tau = 0.75\)</span>:</strong></p>
<ul>
<li>MSBM: <span class="math inline">\(W_2 = 0.160\)</span></li>
<li>TIGON: <span class="math inline">\(W_2 = 0.155\)</span></li>
</ul>
<p><strong>Marginals are nearly identical</strong> — yet the trajectories are qualitatively different!</p>
<p>Only a path-level metric can expose this discrepancy.</p>
</div><div class="column" style="width:50%;">
<p><img data-src="figures/petal_zoom_inset_tau075_leftbranch_msbm_vs_tigon.png" style="width:95.0%"></p>
</div></div>
</section>
<section id="our-approach-overview" class="slide level2 scrollable">
<h2>Our Approach: Overview</h2>
<blockquote>
<p><strong>Key idea:</strong> Treat path measures as <em>first-class citizens</em> and estimate KL divergence directly between them.</p>
</blockquote>
<p><strong>Our contributions:</strong></p>
<ol type="1">
<li><p><strong>FKL estimator</strong> — tractable KL divergence between probability measures on function space, via infinite-dimensional flow theory (FFM)</p></li>
<li><p><strong>Benchmark</strong> — systematic study showing five widely-used marginal metrics produce inconsistent rankings</p></li>
<li><p><strong>Empirical validation</strong> — FKL provides coherent, consistent rankings aligned with visual judgement</p></li>
</ol>
</section></section>
<section>
<section id="background" class="title-slide slide level1 center">
<h1>Background</h1>

</section>
<section id="hilbert-space-setting" class="slide level2">
<h2>Hilbert Space Setting</h2>
<p>Let <span class="math inline">\(\mathcal{H}\)</span> be a real separable Hilbert space with inner product <span class="math inline">\(\langle \cdot, \cdot \rangle_{\mathcal{H}}\)</span> and countable ONB <span class="math inline">\(\{e_k\}_{k \in \mathbb{N}}\)</span>.</p>
<p>For <span class="math inline">\(K \in \mathbb{N}\)</span>, define the canonical projection <span class="math inline">\(\pi_K : \mathcal{H} \to \mathbb{R}^K\)</span> by: <span class="math display">\[\pi_K(x) = \bigl(\langle x, e_1 \rangle, \ldots, \langle x, e_K \rangle\bigr)\]</span></p>
<p>Consider two independent <span class="math inline">\(\mathcal{H}\)</span>-valued random variables:</p>
<ul>
<li><span class="math inline">\(X_0 \sim \mu_0 = \mathcal{N}(0, C)\)</span> — Gaussian reference with <strong>trace-class</strong> covariance <span class="math inline">\(C\)</span></li>
<li><span class="math inline">\(X_1 \sim \mu_1\)</span> — the data distribution</li>
</ul>
<p>The <strong>Cameron–Martin space</strong> is represented as <span class="math inline">\(\mathcal{H}_C\)</span>.</p>
</section>
<section id="functional-flow-matching-ffm" class="slide level2">
<h2>Functional Flow Matching (FFM)</h2>
<p>Construct the <strong>linear interpolation</strong> between <span class="math inline">\(X_0\)</span> and <span class="math inline">\(X_1\)</span>: <span class="math display">\[X_t = (1-t) X_0 + t X_1, \quad t \in [0,1], \qquad \mu_t = \mathrm{Law}(X_t)\]</span></p>
<p>A <strong>velocity field</strong> <span class="math inline">\(v : \mathcal{H} \times [0,1] \to \mathcal{H}\)</span> <strong>generates</strong> the path <span class="math inline">\((\mu_t)\)</span> via the continuity equation: <span class="math display">\[\int_{\mathcal{H}} \varphi(x,1)\,d\mu_1 - \int_{\mathcal{H}} \varphi(x,0)\,d\mu_0 = \int_0^1 \int_{\mathcal{H}} \bigl(\partial_t \varphi + \langle v_t(x), \nabla_x \varphi \rangle\bigr)\,d\mu_t\,dt\]</span></p>
<p><strong>Training:</strong> minimize the tractable conditional flow-matching loss</p>
<p><strong>Generation:</strong> simulate the learned ODE <span class="math inline">\(\partial_t \phi_t(x) = v_\theta(\phi_t(x), t)\)</span> from <span class="math inline">\(x \sim \mu_0\)</span></p>
</section>
<section id="kl-divergence-on-function-space" class="slide level2 scrollable">
<h2>KL Divergence on Function Space</h2>
<p><strong>Setup:</strong> two distributions <span class="math inline">\(\nu^A\)</span> and <span class="math inline">\(\nu^B\)</span> on <span class="math inline">\(\mathcal{H}\)</span>, sharing Gaussian reference <span class="math inline">\(\mu_0 = \mathcal{N}(0, C)\)</span>.</p>
<p><span class="math display">\[\mathrm{KL}(\nu^A \| \nu^B) = \begin{cases} \displaystyle \int_{\mathcal{H}} \log \frac{d\nu^A}{d\nu^B}\,d\nu^A &amp; \text{if } \nu^A \ll \nu^B \\ +\infty &amp; \text{otherwise} \end{cases}\]</span></p>
<p><strong>Two assumptions required:</strong></p>
<ol type="1">
<li><strong>Assumption 2.1 (Radon–Nikodym):</strong> <span class="math inline">\(\nu^A \ll \nu^B\)</span>, and <span class="math inline">\(\frac{d\nu^A}{d\nu^B} \leq M\)</span> <span class="math inline">\(\nu^B\)</span>-a.s. for some <span class="math inline">\(M &lt; \infty\)</span></li>
<li><strong>Assumption 2.2 (Cameron–Martin support):</strong> both <span class="math inline">\(\nu^A\)</span> and <span class="math inline">\(\nu^B\)</span> are supported on <span class="math inline">\(\mathcal{H}_C\)</span></li>
</ol>
</section>
<section id="absolute-continuity-and-kl-divergence" class="slide level2">
<h2>Absolute Continuity and KL Divergence</h2>
<p>Under Assumptions 2.1–2.2, for <span class="math inline">\(t \in [0,1)\)</span>, we assume <strong>absolute continuity</strong> <span class="math inline">\(\mu^A_t \ll \mu^B_t\)</span> with density ratio <span class="math inline">\(r_t(x) := \frac{d\mu^A_t}{d\mu^B_t}(x)\)</span>.</p>
<blockquote>
<p><strong>Lemma 3.4:</strong> Under mild regularity, the KL divergence between path measures is: <span class="math display">\[\mathrm{KL}(\nu^A \| \nu^B) = \int_0^1 \int_{\mathcal{H}} \langle v_t^A(x) - v_t^B(x), \nabla_x \log r_t(x) \rangle_{\mathcal{H}} \, d\mu_t^A(x) \, dt\]</span></p>
</blockquote>
<p>The <strong>score difference</strong> <span class="math inline">\(\nabla_x \log r_t(x)\)</span> is computed via a reference measure <span class="math inline">\(\rho_t\)</span>: <span class="math display">\[\nabla_x \log r_t(x) = \nabla_x \log \frac{d\mu_t^A}{d\rho_t}(x) - \nabla_x \log \frac{d\mu_t^B}{d\rho_t}(x)\]</span></p>
</section></section>
<section>
<section id="method" class="title-slide slide level1 center">
<h1>Method</h1>

</section>
<section id="step-1-basis-projection" class="slide level2">
<h2>Step 1: Basis Projection</h2>
<p>For <span class="math inline">\(K \in \mathbb{N}\)</span>, define projected measures <span class="math inline">\(\hat{\mu}^{A,B}_{t,K} = (\hat{\pi}_K)_\# \mu^{A,B}_t\)</span>.</p>
<p>The projected density ratio is <span class="math inline">\(r^K_t = \frac{d\hat{\mu}^A_{t,K}}{d\hat{\mu}^B_{t,K}} = \mathbb{E}_{P^B}[r_t \mid \mathcal{G}_K]\)</span>, with <span class="math inline">\(\mathcal{G}_K = \sigma(\hat{\pi}^K(X_t))\)</span>.</p>
<p>From the <strong>weak continuity equation</strong> with <span class="math inline">\(r^K_0 = 1\)</span> (<span class="math inline">\(P^B\)</span>-a.s.): <span class="math display">\[\mathrm{KL}(\nu^A_K \| \nu^B_K) = \int_0^1 \int_{\mathcal{H}} \left(\partial_t \log r^K_t(x) + \langle v^A_t(x), \nabla_x \log r^K_t(x) \rangle \right) d\mu^A_t(x)\,dt\]</span></p>
</section>
<section id="step-2-combining-the-continuity-equations" class="slide level2">
<h2>Step 2: Combining the Continuity Equations</h2>
<p>From the continuity equation: <span class="math display">\[\int_0^1 \int_{\mathcal{H}} \partial_t \log r^K_t(x)\,d\mu^A_t(x)\,dt = -\int_0^1 \int_{\mathcal{H}} \langle v^B_t(x), \nabla_x \log r^K_t(x) \rangle\,d\mu^A_t(x)\,dt\]</span></p>
<p>Substituting back: <span class="math display">\[\mathrm{KL}(\nu^A_K \| \nu^B_K) = \int_0^1 \int_{\mathcal{H}} \langle v^A_t(x) - v^B_t(x),\, \nabla_x \log r^K_t(x) \rangle\,d\mu^A_t(x)\,dt\]</span></p>
<p>Note that <span class="math inline">\(\mathrm{KL}(\nu^A_K \| \nu^B_K) \to \mathrm{KL}(\nu^A \| \nu^B)\)</span> as <span class="math inline">\(K \to \infty\)</span>.</p>
</section>
<section id="step-3-expressing-the-log-gradient-via-velocity" class="slide level2">
<h2>Step 3: Expressing the Log-Gradient via Velocity</h2>
<p>The logarithmic gradients can be expressed as: <span class="math display">\[\nabla_x \log \frac{d\mu^{A,B}_t}{d\rho_t}(x) = \frac{t}{(1-t)^2} C^{-1} \mathbb{E}_{P^{A,B}}[X_1 \mid X_t = x]\]</span></p>
<p>For the linear interpolation used in FFM: <span class="math display">\[v^{A,B}_t(x) = \frac{1}{1-t}\mathbb{E}_{P^{A,B}}[X_1 \mid X_t = x] - \frac{x}{1-t}\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> The log-gradient of <span class="math inline">\(r_t = \frac{d\mu^A_t}{d\mu^B_t}\)</span> can be expressed entirely in terms of <span class="math inline">\(v^A_t - v^B_t\)</span>.</p>
</section>
<section id="the-fkl-formula" class="slide level2">
<h2>The FKL Formula</h2>
<p><span class="math display">\[\boxed{\mathrm{KL}(\nu^A \| \nu^B) = \int_0^1 \int_{\mathcal{H}} \frac{t}{1-t} \left\| v^A_t(x) - v^B_t(x) \right\|^2_{\mathcal{H}_{\mu_0}} d\mu^A_t(x)\,dt}\]</span></p>
<blockquote>
<p><strong>Interpretation:</strong> KL divergence between two trajectory distributions is quantified by the difference in their velocity fields, integrated over time and over <span class="math inline">\(\mu^A_t\)</span>.</p>
</blockquote>
<ul>
<li>The weight <span class="math inline">\(\frac{t}{1-t}\)</span> increases toward <span class="math inline">\(t=1\)</span>: discrepancies at later times are penalized more</li>
<li>The norm is in <span class="math inline">\(\mathcal{H}_{\mu_0}\)</span> — the covariance operator <span class="math inline">\(C\)</span> regularizes the comparison</li>
</ul>
</section>
<section id="estimation-algorithm" class="slide level2 scrollable">
<h2>Estimation Algorithm</h2>
<p><strong>Step 1 — Train a velocity field network, conditioning on the class:</strong></p>
<p>Given trajectory samples from <span class="math inline">\(\nu^A\)</span> and <span class="math inline">\(\nu^B\)</span>, train <span class="math inline">\(v^A_\theta\)</span> and <span class="math inline">\(v^B_\theta\)</span> with a class-conditional FFM loss.</p>
<p><strong>Step 2 — Monte Carlo estimation of FKL:</strong></p>
<ol type="1">
<li>Sample <span class="math inline">\(x^A_1 \sim \nu^A\)</span>, <span class="math inline">\(\; t \sim \mathcal{U}[0,1]\)</span>, <span class="math inline">\(\; x_0 \sim \mathcal{N}(0, C)\)</span></li>
<li>Construct interpolation: <span class="math inline">\(x^A_t = t\, x^A_1 + (1-t)\, x_0 \;\sim\; \mu^A_t\)</span></li>
<li>Evaluate both velocity fields at <span class="math inline">\((x^A_t, t)\)</span></li>
<li>Compute <span class="math inline">\(\frac{t}{1-t} \| v^A_\theta(x^A_t) - v^B_\theta(x^A_t) \|^2_{C^{1/2}}\)</span></li>
<li>Average over samples <span class="math inline">\(\Rightarrow\)</span> FKL estimate</li>
</ol>
<p><strong>No ODE integration required</strong> — cost proportional to a single forward pass through two networks.</p>
</section>
<section id="implementation-details" class="slide level2">
<h2>Implementation Details</h2>
<p><strong>Architecture:</strong> Mesh-Informed Neural Operator (MINO) — transformer version</p>
<p><strong>Projection:</strong> all computations use <span class="math inline">\(K\)</span>-mode truncation of the ONB <span class="math inline">\(\{e_k\}\)</span></p>
<p><strong>Noise:</strong> <strong>trace-class</strong> noise (Matérn or rougher data covariance) rather than white noise</p>
<ul>
<li>Better generation quality and more robust KL estimation</li>
<li>Resolution invariant</li>
</ul>
<p><strong>Asymmetry:</strong> both <span class="math inline">\(\mathrm{KL}(\nu^A \| \nu^B)\)</span> and <span class="math inline">\(\mathrm{KL}(\nu^B \| \nu^A)\)</span> are reported:</p>
<ul>
<li>Forward KL: penalizes missing coverage of the reference</li>
<li>Reverse KL: penalizes hallucinated mass outside the reference support</li>
</ul>
</section></section>
<section>
<section id="empirical-validation" class="title-slide slide level1 center">
<h1>Empirical Validation</h1>

</section>
<section id="special-case-1-gaussian-measures" class="slide level2">
<h2>Special Case 1: Gaussian Measures</h2>
<p>Consider <span class="math inline">\(\nu^A = \mathcal{N}(m^A, R)\)</span> and <span class="math inline">\(\nu^B = \mathcal{N}(m^B, R)\)</span> on <span class="math inline">\(\mathcal{H} = L^2(\mathbb{T}; \mathbb{R})\)</span> with Matérn covariance <span class="math inline">\(R\)</span>.</p>
<p><strong>Closed-form KL:</strong> <span class="math display">\[\mathrm{KL}(\nu^A \| \nu^B) = \frac{1}{2}\|m^A - m^B\|^2_{\mathcal{H}_R}\]</span></p>
<p>Setting <span class="math inline">\(m^A = \cos(2\pi x)\)</span>, <span class="math inline">\(m^B = 0\)</span>; ONB <span class="math inline">\(\{e_k(x) = e^{2\pi i k \cdot x}\}\)</span> with <span class="math inline">\(\mathcal{K}e_k = \lambda_k e_k\)</span>, <span class="math inline">\(\lambda_k = \sigma^2(4\pi^2 k^2 + \tau^2)^{-\alpha}\)</span>.</p>
<blockquote>
<p><strong>Validation:</strong> FKL estimator closely matches the closed-form value, and is resolution invariant.</p>
</blockquote>
</section>
<section id="special-case-1-results" class="slide level2">
<h2>Special Case 1: Results</h2>
<div class="columns">
<div class="column" style="width:65%;">
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Case</th>
<th><span class="math inline">\(D\)</span></th>
<th><span class="math inline">\(f\)</span></th>
<th><span class="math inline">\(s\)</span></th>
<th>Fwd Analytic</th>
<th>Fwd Estim.</th>
<th>Rev Analytic</th>
<th>Rev Estim.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>1</td>
<td>0.5</td>
<td>3.64</td>
<td>3.95</td>
<td>3.64</td>
<td>3.88</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>1</td>
<td>1.5</td>
<td>32.79</td>
<td>32.61</td>
<td>32.79</td>
<td>33.31</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1</td>
<td>3</td>
<td>1.5</td>
<td>50.00</td>
<td>49.58</td>
<td>50.00</td>
<td>49.00</td>
</tr>
<tr class="even">
<td>4</td>
<td>1</td>
<td>5</td>
<td>1.5</td>
<td>103.74</td>
<td>104.46</td>
<td>103.74</td>
<td>100.58</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2</td>
<td>1</td>
<td>0.5</td>
<td>7.29</td>
<td>6.77</td>
<td>7.29</td>
<td>6.72</td>
</tr>
<tr class="even">
<td>6</td>
<td>3</td>
<td>1</td>
<td>0.5</td>
<td>10.93</td>
<td>10.48</td>
<td>10.93</td>
<td>10.49</td>
</tr>
<tr class="odd">
<td>7</td>
<td>5</td>
<td>1</td>
<td>0.5</td>
<td>18.22</td>
<td>22.32</td>
<td>18.22</td>
<td>22.28</td>
</tr>
<tr class="even">
<td>8</td>
<td>10</td>
<td>1</td>
<td>0.5</td>
<td>36.43</td>
<td>45.12</td>
<td>36.43</td>
<td>45.73</td>
</tr>
</tbody>
</table>
<p><em>Gaussian Measure: analytic vs estimated functional KL.</em></p>
</div><div class="column" style="width:35%;">
<p><img data-src="figures/gm_analytic_vs_estimated.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="special-case-2-linear-sdes-girsanov" class="slide level2">
<h2>Special Case 2: Linear SDEs (Girsanov)</h2>
<p>Two SDEs with same diffusion, different drifts: <span class="math display">\[A: dY_t = c^A Y_t\,dt + g\,dW_t, \qquad B: dY_t = c^B Y_t\,dt + g\,dW_t\]</span></p>
<p><strong>Girsanov’s theorem + Itô isometry</strong> give the closed-form KL: <span class="math display">\[\mathrm{KL}(\nu^A \| \nu^B) = \frac{(c^A - c^B)^2}{2g^2} \left[ (M_0 + S_0)\,\frac{e^{2c^A} - 1}{2c^A} + \frac{g^2 D}{2c^A}\!\left(\frac{e^{2c^A} - 1}{2c^A} - 1\right) \right]\]</span></p>
<p>where <span class="math inline">\(M_0 = \|Y_0\|^2\)</span>, <span class="math inline">\(S_0 = \text{Tr}(\Sigma_0)\)</span>.</p>
<p>Our FKL estimates match this ground truth closely across all tested settings.</p>
</section>
<section id="special-case-2-results" class="slide level2">
<h2>Special Case 2: Results</h2>
<div class="columns">
<div class="column" style="width:70%;">
<table class="caption-top">
<colgroup>
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Case</th>
<th><span class="math inline">\(D\)</span></th>
<th><span class="math inline">\(c_A\)</span></th>
<th><span class="math inline">\(c_B\)</span></th>
<th><span class="math inline">\(g\)</span></th>
<th>Fwd Analytic</th>
<th>Fwd Estim.</th>
<th>Rev Analytic</th>
<th>Rev Estim.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>0.01</td>
<td>1.50</td>
<td>0.75</td>
<td>8.93</td>
<td>8.87</td>
<td>54.71</td>
<td>53.77</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>0.10</td>
<td>2.00</td>
<td>0.75</td>
<td>15.89</td>
<td>13.89</td>
<td>186.19</td>
<td>200.64</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2</td>
<td>0.01</td>
<td>1.50</td>
<td>0.75</td>
<td>17.86</td>
<td>18.05</td>
<td>109.43</td>
<td>127.67</td>
</tr>
<tr class="even">
<td>4</td>
<td>3</td>
<td>0.01</td>
<td>1.50</td>
<td>0.75</td>
<td>26.79</td>
<td>34.58</td>
<td>164.14</td>
<td>145.06</td>
</tr>
<tr class="odd">
<td>5</td>
<td>5</td>
<td>0.01</td>
<td>1.50</td>
<td>1.00</td>
<td>26.34</td>
<td>32.82</td>
<td>158.22</td>
<td>135.28</td>
</tr>
</tbody>
</table>
<p><em>Linear SDE: analytic (Girsanov) vs estimated FKL.</em></p>
</div><div class="column" style="width:30%;">
<p><img data-src="figures/sde_linear_analytic_vs_estimated.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="fkl-vs-upsampling-ratio" class="slide level2">
<h2>FKL vs Upsampling Ratio</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/kl_upsample_GM.png" style="width:100.0%"></p>
<figcaption>Gaussian Measure</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/kl_upsample_SDE.png" style="width:100.0%"></p>
<figcaption>Linear SDE</figcaption>
</figure>
</div>
</div></div>
<ul>
<li><strong>Trace-class noise:</strong> stable KL estimates at all resolutions</li>
<li><strong>White noise:</strong> degrades at super-resolution — trace-class noise covariance is essential</li>
</ul>
</section></section>
<section>
<section id="experiments" class="title-slide slide level1 center">
<h1>Experiments</h1>

</section>
<section id="ti-methods-compared" class="slide level2">
<h2>TI Methods Compared</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 32%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Paradigm</th>
<th>Key property</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SBIRR</td>
<td>Schrödinger Bridge</td>
<td>Gradient fields + stochasticity; iterative ref. refinement</td>
</tr>
<tr class="even">
<td>vSB</td>
<td>Schrödinger Bridge</td>
<td>Vanilla IPF-based; snapshot matching</td>
</tr>
<tr class="odd">
<td>MSBM</td>
<td>Multi-marginal SB</td>
<td>Iterative Markovian Fitting; multi-snapshot constraints</td>
</tr>
<tr class="even">
<td>MFL</td>
<td>Mean-Field Langevin</td>
<td>Path-space optimization; min-entropy w.r.t. Wiener measure</td>
</tr>
<tr class="odd">
<td>AM</td>
<td>Action Matching</td>
<td>Minimizes kinetic energy; optional entropic variant</td>
</tr>
<tr class="even">
<td>TIGON</td>
<td>ODE-based</td>
<td>Neural ODE; dynamic unbalanced OT + growth</td>
</tr>
</tbody>
</table>
<p>Reference: <strong>VAL</strong> = resampled ground-truth trajectories (oracle upper bound)</p>
</section>
<section id="marginal-metrics-evaluated" class="slide level2">
<h2>Marginal Metrics Evaluated</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 27%">
<col style="width: 18%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Acronym</th>
<th>Type</th>
<th>Property</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Earth Mover’s Distance</td>
<td>EMD (<span class="math inline">\(W_1\)</span>)</td>
<td>OT</td>
<td>Geometry-aware</td>
</tr>
<tr class="even">
<td>2-Wasserstein Distance</td>
<td><span class="math inline">\(W_2\)</span></td>
<td>OT</td>
<td>Quadratic cost</td>
</tr>
<tr class="odd">
<td>Sliced Wasserstein Distance</td>
<td>SWD</td>
<td>OT</td>
<td>Random projections</td>
</tr>
<tr class="even">
<td>Max-sliced Wasserstein</td>
<td>MWD</td>
<td>OT</td>
<td>Max-sliced variant</td>
</tr>
<tr class="odd">
<td>Maximum Mean Discrepancy</td>
<td>MMD</td>
<td>Kernel</td>
<td>RBF kernel; bandwidth-dependent</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[W_p(\mu,\nu) = \left(\inf_{\gamma\in\Pi(\mu,\nu)}\int \|x-y\|^p\,d\gamma\right)^{1/p}\]</span> <span class="math display">\[\mathrm{MMD}^2(\mu,\nu) = \mathbb{E}_{x,x'\sim\mu}[k(x,x')] - 2\,\mathbb{E}_{x\sim\mu,y\sim\nu}[k(x,y)] + \mathbb{E}_{y,y'\sim\nu}[k(y,y')]\]</span></p>
<blockquote>
<p><strong>Limitation:</strong> All these metrics operate on marginals — blind to temporal coupling structure.</p>
</blockquote>
</section>
<section id="synthetic-datasets" class="slide level2">
<h2>Synthetic Datasets</h2>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>Lotka–Volterra</strong></p>
<ul>
<li>Predator-prey SDE dynamics</li>
<li>9 snapshots (5 train, 4 val)</li>
<li>100 samples/snapshot</li>
<li>Non-linear oscillatory behavior</li>
</ul>
</div><div class="column" style="width:33%;">
<p><strong>Repressilator</strong></p>
<ul>
<li>3-gene regulatory oscillator</li>
<li>Cyclic inhibition loop</li>
<li>11 snapshots (6 train, 5 val)</li>
<li>100 samples/snapshot</li>
</ul>
</div><div class="column" style="width:33%;">
<p><strong>Petal</strong></p>
<ul>
<li>Bifurcations &amp; merges</li>
<li>Mimics cell differentiation</li>
<li>5 snapshots (all training)</li>
<li>500 samples/snapshot</li>
</ul>
</div></div>
<p><strong>Ground-truth trajectories available</strong> <span class="math inline">\(\Rightarrow\)</span> FKL computed against true path measure</p>
</section>
<section id="real-single-cell-rna-seq-datasets" class="slide level2">
<h2>Real Single-Cell RNA-seq Datasets</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Embryoid Body (EB)</strong></p>
<ul>
<li>Moon et al., 2019</li>
<li>3 training + 2 validation timepoints</li>
<li>300 cells per snapshot</li>
<li>5 dimensions (PCA-reduced)</li>
<li>Stem cell differentiation</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Human Embryonic Stem Cell (hESC)</strong></p>
<ul>
<li>Chu et al., 2016</li>
<li>3 training + 2 validation snapshots</li>
<li>92 / 66 / 138 cells (train)</li>
<li>102 / 172 cells (validation)</li>
<li>5 dimensions (PCA-reduced)</li>
</ul>
</div></div>
<blockquote>
<p><strong>No ground-truth trajectories on real data.</strong> We use <strong>SBIRR</strong> as reference: it models differentiation via gradient fields with stochasticity, matching biological intuition of Waddington’s landscape.</p>
</blockquote>
</section></section>
<section>
<section id="results-marginal-metrics" class="title-slide slide level1 center">
<h1>Results: Marginal Metrics</h1>

</section>
<section id="synthetic-data-trajectory-visualizations" class="slide level2">
<h2>Synthetic Data, Trajectory Visualizations</h2>
<div id="fig-trajectories" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-trajectories-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><img data-src="figures/lv_trajectories_full2.png" style="width:85.0%"></p>
<p><img data-src="figures/repressilator_trajectories_full.png" style="width:85.0%"></p>
<p><img data-src="figures/petal_trajectories_full2.png" style="width:85.0%"></p>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trajectories-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>Trajectory Inference Results.</strong> Top: Lotka–Volterra. Middle: Repressilator. Bottom: Petal. Colored curves: GT; black curves: generated; scattered points: validation snapshots.
</figcaption>
</figure>
</div>
</section>
<section id="critical-difference-analysis" class="slide level2">
<h2>Critical Difference Analysis</h2>
<div class="columns">
<div class="column" style="width:57%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/cd-diagram_lv.png" style="width:92.0%"></p>
<figcaption>Lotka–Volterra</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/cd-diagram_repr.png" style="width:92.0%"></p>
<figcaption>Repressilator</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/cd-diagram_petal.png" style="width:92.0%"></p>
<figcaption>Petal</figcaption>
</figure>
</div>
</div><div class="column" style="width:41%;">
<p>CD analysis ranks marginal-metric methods by significance:</p>
<ul>
<li><strong>LV &amp; Repr:</strong> methods largely tied — rankings <strong>not significant</strong></li>
<li><strong>Petal:</strong> CD ranks MSBM between <em>worst</em> methods; FKL ranks it <strong>best</strong></li>
<li><strong>Agreement:</strong> VAL best overall; SBIRR near top</li>
</ul>
<blockquote>
<p>In general, marginal metrics are not significant. FKL provides principled ranking even when CD gives weak guidance.</p>
</blockquote>
</div></div>
</section>
<section id="non-identifiability-the-core-issue" class="slide level2">
<h2>Non-Identifiability: The Core Issue</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><img data-src="figures/petal_zoom_inset_tau075_leftbranch_msbm_vs_tigon.png" style="width:100.0%"></p>
</div><div class="column" style="width:55%;">
<p><strong>The non-identifiability principle:</strong></p>
<p>Any finite set of marginals is consistent with <em>infinitely many</em> path measures.</p>
<p>Methods that connect point clouds (TIGON) can score well on marginals while generating unrealistic temporal behavior.</p>
<p>SB methods (vSB, MSBM) focus on snapshot matching and provide limited control over intermediate dynamics unless additional structure is imposed (as in SBIRR).</p>
<p><strong>Only FKL can distinguish them.</strong></p>
</div></div>
</section>
<section id="limitations-of-marginal-metrics" class="slide level2">
<h2>Limitations of Marginal Metrics</h2>
<ul>
<li><strong>Inconsistent rankings:</strong> snapshot-based criteria produce contradictory orderings across datasets</li>
<li><strong>Favor wrong models:</strong> methods may score well on marginals while generating dynamics inconsistent with the true process</li>
<li><strong>Non-identifiability:</strong> any finite set of marginals is consistent with infinitely many path measures — marginals cannot discriminate between trajectory models</li>
<li><strong>CD confirms:</strong> even statistical testing of marginal-metric rankings yields largely non-significant results (LV, Repressilator) or actively misleading ones (Petal)</li>
</ul>
</section></section>
<section>
<section id="results-fkl-rankings" class="title-slide slide level1 center">
<h1>Results: FKL Rankings</h1>

</section>
<section id="fkl-rankings-across-datasets" class="slide level2">
<h2>FKL: Rankings Across Datasets</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>LV Fwd</th>
<th>LV Rev</th>
<th>Repr Fwd</th>
<th>Repr Rev</th>
<th>Petal Fwd</th>
<th>Petal Rev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VAL</td>
<td>7.85 ± 0.43</td>
<td>7.82 ± 0.41</td>
<td>5.21 ± 0.08</td>
<td>5.19 ± 0.08</td>
<td>4.00 ± 0.04</td>
<td>3.88 ± 0.05</td>
</tr>
<tr class="even">
<td><strong>SBIRR</strong></td>
<td><strong>30.6 ± 0.3</strong></td>
<td><strong>32.5 ± 0.7</strong></td>
<td><strong>13.4 ± 0.3</strong></td>
<td><strong>16.1 ± 0.3</strong></td>
<td>21.5 ± 0.2</td>
<td>34.3 ± 0.6</td>
</tr>
<tr class="odd">
<td>vSB</td>
<td>89.8 ± 2.5</td>
<td>87.4 ± 2.4</td>
<td>31.2 ± 0.6</td>
<td>31.4 ± 0.6</td>
<td>24.0 ± 0.3</td>
<td>37.1 ± 0.8</td>
</tr>
<tr class="even">
<td><strong>MSBM</strong></td>
<td>56.5 ± 2.8</td>
<td>37.3 ± 1.0</td>
<td>30.5 ± 0.7</td>
<td>19.8 ± 0.2</td>
<td><strong>13.6 ± 0.1</strong></td>
<td><strong>16.1 ± 0.2</strong></td>
</tr>
<tr class="odd">
<td>MFL</td>
<td>38.7 ± 0.7</td>
<td>153.4 ± 9.9</td>
<td>26.4 ± 0.5</td>
<td>35.8 ± 0.5</td>
<td>42.3 ± 1.1</td>
<td>81.5 ± 5.6</td>
</tr>
<tr class="even">
<td>AM</td>
<td>35.2 ± 0.7</td>
<td>49.1 ± 1.6</td>
<td>27.4 ± 0.4</td>
<td>435.8 ± 17.4</td>
<td>16.9 ± 0.4</td>
<td>32.7 ± 0.9</td>
</tr>
<tr class="odd">
<td>TIGON</td>
<td>66.6 ± 3.1</td>
<td>51.3 ± 0.8</td>
<td>18.8 ± 0.3</td>
<td>17.0 ± 0.1</td>
<td>40.0 ± 3.1</td>
<td>17.8 ± 0.3</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>SBIRR</strong> ranks best on LV &amp; Repressilator; <strong>MSBM</strong> best on Petal — consistent with visual inspection</li>
<li><strong>TIGON</strong> passes through correct snapshot regions but generates a wrong <em>smooth spiral</em>; FKL correctly penalizes this</li>
<li><strong>AM / Repressilator:</strong> fwd = 27.4, rev = 435.8 → strong hallucination undetected by marginal metrics</li>
</ul>
</section>
<section id="mode-seeking-and-mode-coverage" class="slide level2">
<h2>Mode Seeking and Mode Coverage</h2>
<p><span class="math inline">\(\mathrm{KL}(\nu^A \| \nu^B)\)</span>: penalizes reference support <em>not covered</em> by <span class="math inline">\(\nu^B\)</span> <span class="math inline">\(\;\Rightarrow\;\)</span> <strong>mode coverage</strong></p>
<p><span class="math inline">\(\mathrm{KL}(\nu^B \| \nu^A)\)</span>: penalizes mass that <span class="math inline">\(\nu^B\)</span> places <em>outside</em> the reference <span class="math inline">\(\;\Rightarrow\;\)</span> <strong>hallucination</strong></p>
<p>When <span class="math inline">\(\mathrm{KL}(\nu^B \| \nu^A) \gg \mathrm{KL}(\nu^A \| \nu^B)\)</span>, the method generates trajectories unsupported by the reference.</p>
<ul>
<li><strong>AM / Repressilator</strong> — fwd <span class="math inline">\(= 27.4\)</span>, rev <span class="math inline">\(= 435.8\)</span>: MMD saturates, masking that AM places mass far outside the reference support</li>
<li><strong>MFL / Lotka-Volterra</strong> — fwd <span class="math inline">\(= 38.7\)</span>, rev <span class="math inline">\(= 153.4\)</span>: forward score alone ranks MFL near SBIRR; reverse KL exposes strong hallucination</li>
<li><strong>MSBM / Petal</strong> — fwd <span class="math inline">\(= 13.6\)</span>, rev <span class="math inline">\(= 16.1\)</span>: nearly symmetric; trajectories well-aligned in both directions</li>
</ul>
</section>
<section id="real-data-trajectory-visualizations" class="slide level2">
<h2>Real Data: Trajectory Visualizations</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/3D_trajectories_comparison_eb_dataset_new_full.png" style="width:100.0%"></p>
<figcaption>EB dataset</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/3D_trajectories_comparison_hesc_dataset_full_with_points.png" style="width:100.0%"></p>
<figcaption>hESC dataset</figcaption>
</figure>
</div>
</section>
<section id="real-data-results-summary" class="slide level2">
<h2>Real Data Results Summary</h2>
<p><strong>EB dataset</strong> — FKL prefers MFL (fwd) and MSBM (rev); TIGON scores highest on some marginal metrics at <span class="math inline">\(\tau=0.25\)</span> but has FKL = 126, the worst by far.</p>
<p><strong>hESC dataset</strong> — MFL achieves lowest forward FKL (95.1); TIGON wins most marginal metrics at <span class="math inline">\(\tau=0.25\)</span> but scores FKL = 288.5, the worst.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Method</th>
<th>Marginal Winner?</th>
<th>FKL Best?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>EB</td>
<td>MFL</td>
<td>Partial</td>
<td>✓ (fwd)</td>
</tr>
<tr class="even">
<td>EB</td>
<td>TIGON</td>
<td>At <span class="math inline">\(\tau=0.25\)</span></td>
<td>✗ (worst)</td>
</tr>
<tr class="odd">
<td>hESC</td>
<td>MFL</td>
<td>No</td>
<td>✓ (fwd)</td>
</tr>
<tr class="even">
<td>hESC</td>
<td>TIGON</td>
<td>At <span class="math inline">\(\tau=0.25\)</span></td>
<td>✗ (worst)</td>
</tr>
</tbody>
</table>
<ul>
<li>Marginal metrics are inconsistent also in real-data scenarios</li>
<li>FKL correctly recognizes the difference in underlying dynamics</li>
<li>FKL consistently prefers SB methods for both datasets, matching biological priors</li>
</ul>
</section></section>
<section>
<section id="conclusion" class="title-slide slide level1 center">
<h1>Conclusion</h1>

</section>
<section id="summary" class="slide level2 scrollable">
<h2>Summary</h2>
<ol type="1">
<li><p><strong>Problem:</strong> Marginal-based TI evaluation is fundamentally limited by non-identifiability and inconsistency</p></li>
<li><p><strong>Theoretical contribution:</strong> FKL — a tractable KL estimator between probability measures on function space: <span class="math display">\[\mathrm{KL}(\nu^A \| \nu^B) = \int_0^1 \int_{\mathcal{H}} \frac{t}{1-t} \|v^A_t(x) - v^B_t(x)\|^2_{\mathcal{H}_{\mu_0}} \,d\mu^A_t\,dt\]</span></p></li>
<li><p><strong>Empirical finding:</strong> Five standard marginal metrics yield inconsistent, often misleading rankings</p></li>
<li><p><strong>Take-home message:</strong> FKL provides a coherent evaluation metric aligned with visual inspection and quantifies differences in dynamics between trajectory distributions</p></li>
</ol>
</section>
<section id="thank-you-questions" class="slide level2">
<h2>Thank You — Questions?</h2>
<div style="text-align:center; font-size:1.8em; font-weight:bold; margin-top:1em;">
<p>Thank you!</p>
</div>
<div style="text-align:center; margin-top:1.5em;">
<p><strong>Paper:</strong> <em>Relative Entropy Estimation in Function Space: Theory and Applications to Trajectory Inference</em></p>
<p>WANG Chao, NEPOTE Luca, FRANZESE Giulio, MICHIARDI Pietro — EURECOM</p>
<p><em>Preliminary work under review at ICML.</em></p>
</div>
</section>
<section id="references" class="slide level2 unnumbered smaller scrollable">
<h2>References</h2>
<div id="refs" role="list">

</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="lecture_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="lecture_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="lecture_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="lecture_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>