args: !!python/object:argparse.Namespace
  N: 5000
  N_test: 2000
  accelerator: cpu
  arch: tx
  benchmark: custom
  bs: 256
  check_val_every_n_epoch: 1
  debug: true
  devices: 1
  dim: 1
  importance_sampling: true
  lr: 0.001
  max_epochs: 3
  mc_iter: 2
  nb_workers: 0
  o_inf_order: 1
  out_dir: quickstart/
  results_dir: results/
  rho: 0.1
  seed: 3
  setting: 0
  test_epoch: 1
  transformation: ''
  use_ema: true
  warmup_epochs: 1
  weight_s_functions: true
